PickleballApp/Models/Player.cs
using System.ComponentModel.DataAnnotations;

namespace PickleballApp.Models
{
    public class Player
    {
        //EF Core will configure the database to generate this value
        public int PlayerId { get; set; }

        [Required(ErrorMessage = "Please enter a first name.")]
        public string FirstName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a last name.")]
        public string LastName { get; set; } = string.Empty;
        // I will add this at a later date
        //[Required(ErrorMessage = "Please enter a birth date.")]
        ////[Range(DateTime.Today.AddYears(-100), DateTime.Today.AddYears(-5), ErrorMessage = "A Player must be a least 5 years old.")]
        //// I need to create a custom validation type to perform the above code
        //public DateTime BirthDate { get; set; }
        [Required(ErrorMessage = "Please select a gender")]
        public string? Gender { get; set; }

    }
}

PickleballApp/Models/PlayerContext.cs
using Microsoft.EntityFrameworkCore;
using PickleballApp.Models;
namespace PickleballApp.Models
{
    public class PlayerContext : DbContext
    {
        public PlayerContext(DbContextOptions<PlayerContext> options)
            : base(options)
        { }


        public DbSet<Player> Players { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Player>().HasData(
                new Player
                {
                    PlayerId = 1,
                    FirstName = "Augusta",
                    LastName = "Cain",
                    Gender = "Male"
                }, 
                new Player
                {
                    PlayerId = 2,
                    FirstName = "Brian",
                    LastName = "Cain",
                    Gender = "Male"
                },
                new Player
                {
                    PlayerId = 3,
                    FirstName = "Amethyst Cain",
                    LastName = "Cain",
                    Gender = "Female"
                }
                );
        }
        

    }
}

PickleballApp/Models/Team.cs
using System.ComponentModel.DataAnnotations;
//Required to turn off validation for player properties
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
namespace PickleballApp.Models
{
    public class Team
    {
        //EF Core will configure the database to generate this value
        public int TeamId { get; set; }

        [ValidateNever]
        Player Player1 { get; set; } = null!;
        [ValidateNever]
        Player Player2 { get; set; } = null!;

    }
}

PickleballApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PickleballApp.Models;

namespace PickleballApp.Controllers;

public class HomeController : Controller
{
    

    public IActionResult Index()
    {
        return View();
    }

    
}

PickleballApp/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PickleballApp.Models;

namespace PickleballApp.Controllers
{
    public class PlayerController : Controller
    {

        private PlayerContext Context { get; set; }

        // constructor method
        public PlayerController(PlayerContext context)
        {
            Context = context;
        }
        
        // GET: PlayerController
        public IActionResult Index()
        {
            //querying the database to return ALL players ordered by Last name
            List<Player> players =
                Context.Players
                .OrderBy(m => m.LastName)
                .ToList();

            return View(players);
        }


        // GET: PlayerController/Create
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Edit";

            return View("Edit", new Player());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            var player = Context.Players.Find(id);

            return View(player);
        }

        [HttpPost]
        public IActionResult Edit(Player player)
        {
            if (ModelState.IsValid)
            {
                if(player.PlayerId == 0)
                {
                    Context.Players.Add(player);
                }
                else
                {
                    Context.Players.Update(player);
                }

                Context.SaveChanges();

                return RedirectToAction("Index", "Player");
            }
            else
            {
                ViewBag.Action = (player.PlayerId == 0) ? "Add" : "Edit";

                return View(player);
            }
        }

        // GET: PlayerController/Delete/5
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var player = Context.Players.Find(id);


            return View(player);
        }

        // POST: PlayerController/Delete/5
        [HttpPost]
        public IActionResult Delete(Player player)
        {
            Context.Players.Remove(player);
            Context.SaveChanges();

            return RedirectToAction("Index", "Player");
        }
    }
}

PickleballApp/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PickleballApp.Models;


namespace PickleballApp.Controllers
{
    public class TeamController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PickleballApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <h1>Welcome to your home page!</h1>

PickleballApp/Views/Player/Delete.cshtml
@model Player
@{
	ViewData["Title"] = "Delete Player";
}

<h2>Confirm Deletion</h2>
<h3>@Model.FirstName @Model.LastName</h3>


<form asp-action="Delete" method="post">

	<input type="hidden" asp-for="PlayerId" />

	<button type="submit" class="btn btn-danger">Delete</button>
	<a asp-controller="Player" asp-action="Index"
		class="btn btn-secondary">Cancel</a>

</form>

PickleballApp/Views/Player/Edit.cshtml
@model Player
@{
	string title = ViewBag.Action + " Player";
	ViewData["Title"] = title;
}

<h2>@ViewBag.Title</h2>

<form asp-action="Edit" method="post">
	<div asp-validation-summary="All" class="text-danger"></div>

	<div class="mb-3">
		<label asp-for="FirstName" class="form-label">First Name</label>
		<input asp-for="FirstName" class="form-control" />
	</div>

	<div class="mb-3">
		<label asp-for="LastName" class="form-label">Last Name</label>
		<input asp-for="LastName" class="form-control" />
	</div>

	<div class="mb-3">
		<label asp-for="Gender" class="form-label">Gender</label>
		<select asp-for="Gender" class="form-select">
			<option value="Male">Male</option>
			<option value="Female">Female</option>
		</select>
	</div>

	<input type="hidden" asp-for = "PlayerId" />

	<button type="submit" class="btn btn-primary">Save</button>
	<a asp-controller="Player" asp-action="Index"
		class="btn btn-secondary">Cancel</a>
</form>

PickleballApp/Views/Player/Index.cshtml
@model List<Player>
@{
    ViewData["Title"] = "List of Players";
}

<div class="mb-2">
    <a asp-controller="Player" asp-action="Add"
        class="btn btn-primary">Add New Player</a>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Gender</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var player in Model)
        {
            <tr>
                <td>@player.FirstName</td>
                <td>@player.LastName</td>
                <td>@player.Gender</td>
                <td>
                    <a asp-controller="Player" asp-action="Edit"
                        asp-route-id="@player.PlayerId" class="btn btn-primary">Edit</a>
                    <a asp-controller="Player" asp-action="Delete"
                        asp-route-id="@player.PlayerId" class="btn btn-close btn-danger" aria-label="Close"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

PickleballApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>
<body>

    <div class="d-flex">
        <div class="bg-dark text-white p-3 vh-100" style="width: 250px;">
            <h5>Pages</h5>
            <a asp-controller="Home" asp-action="Index" class="d-block nav-link">Home</a>
            <a asp-controller="Player" asp-action="Index" class="d-block nav-link">Players</a>
            <a asp-controller="Team" asp-action="Index" class="d-block nav-link">Teams</a>
            <!--This is where links to future pages will go-->
        </div>

        <div class="flex-grow-1 p-4">
            <header class="p-4 mb-3 bg-light border">
                <h1>My Pickleball APP</h1>
            </header>
            @RenderBody()
        </div>
    </div>

</body>
</html>

PickleballApp/Views/Team/Index.cshtml
@model PickleballApp.Models.Team

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View</h1>

<div>
    <h4>Team</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TeamId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>